# Generated by Django 5.2.4 on 2026-02-04 20:53

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='Notification title', max_length=300)),
                ('message', tinymce.models.HTMLField(default='message')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Error_log',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occured', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='Notification title', max_length=300)),
                ('error', tinymce.models.HTMLField(default='message')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='Notification title', max_length=300)),
                ('message', tinymce.models.HTMLField(default='message')),
                ('is_seen', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
