# Generated by Django 5.2.4 on 2025-08-02 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_transaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=100)),
                ('chef', models.CharField(default='chef username', max_length=100)),
                ('type', models.CharField(default='Transaction Type', max_length=100)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('transaction_proof', models.ImageField(upload_to='transaction_proofs/')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(blank=True, default='setting name', max_length=100, null=True)),
                ('setting_value', models.TextField(blank=True, default='setting value', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=100)),
                ('chef', models.CharField(default='chef username', max_length=100)),
                ('type', models.CharField(default='Transaction Type', max_length=100)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('transaction_proof', models.ImageField(upload_to='transaction_proofs/')),
                ('transaction_id', models.TextField(blank=True, default='Transaction UID', null=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0, max_length=20)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('aiu_id', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card', models.ImageField(upload_to='id_card/')),
                ('campaign_points', models.IntegerField(blank=True, default=0, null=True)),
                ('total_deposit', models.IntegerField(blank=True, default=0, null=True)),
                ('total_orders', models.IntegerField(blank=True, default=0, null=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_account_banned', models.BooleanField(default=False)),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_order', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
