# Generated by Django 5.2.4 on 2025-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_campaigns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_orders_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
