# Generated by Django 5.2.4 on 2025-08-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_profile_total_campaigns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='campaign_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_campaigns',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_deposit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_orders_received',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_card/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
