# Generated by Django 5.2.4 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_subscription_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_transaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
