# Generated by Django 5.2.4 on 2025-08-02 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=100)),
                ('food_status', models.CharField(default='cooking', max_length=100)),
                ('title', models.CharField(default='Campaign Title', max_length=100)),
                ('campaign_description', models.TextField(blank=True, null=True)),
                ('food_ids', models.TextField(blank=True, default='Food IDs(comma separated)', null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity_available', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign_history',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=100)),
                ('title', models.CharField(default='Campaign Title', max_length=100)),
                ('campaign_description', models.TextField(blank=True, null=True)),
                ('food_ids', models.TextField(blank=True, default='Food IDs(comma separated)', null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_orders', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chef_name', models.CharField(default='Chef Name', max_length=100)),
                ('chef_description', models.TextField(blank=True, null=True)),
                ('chef_image', models.ImageField(default='chef_images/default.png', upload_to='chef_images/')),
                ('balance', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_deposit', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(default='Expired', max_length=50)),
                ('subscription_ends', models.DateTimeField(auto_now_add=True, null=True)),
                ('campaign_points', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(default='Food Name', max_length=100)),
                ('food_description', models.TextField(blank=True, null=True)),
                ('chef_name', models.CharField(default='Chef Name', max_length=100)),
                ('food_price', models.FloatField(default=0)),
                ('food_image', models.ImageField(default='food_images/default.png', upload_to='food_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('user_address', models.CharField(default='User Address', max_length=255)),
                ('user_phone', models.CharField(default='User Phone', max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('food_price', models.FloatField(default=0)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order_history',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('food_price', models.FloatField(default=0)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
