# Generated by Django 5.2.4 on 2025-08-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='chef_name',
            new_name='chef_username',
        ),
    ]
