# Generated by Django 5.2.4 on 2025-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_chef_name_chef_chef_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='chef_name',
            new_name='chef',
        ),
        migrations.AddField(
            model_name='campaign',
            name='chef',
            field=models.CharField(default='Chef Username', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign_history',
            name='chef',
            field=models.CharField(default='Chef Username', max_length=100),
        ),
    ]
