# Generated by Django 5.2.4 on 2025-08-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_chef_name_food_chef_campaign_chef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='total_orders',
        ),
        migrations.AddField(
            model_name='chef',
            name='last_summary_report',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_april',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_august',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_december',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_february',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_january',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_july',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_june',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_march',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_may',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_november',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_october',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='sales_september',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='total_campaigns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='total_orders_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
