# Generated by Django 5.2.4 on 2025-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_chef_total_orders_chef_last_summary_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='last_summary_report',
        ),
        migrations.AddField(
            model_name='chef',
            name='last_month_sales',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='this_month_sales',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
