# Generated by Django 5.2.4 on 2026-02-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_chef_last_summary_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='food_ids',
        ),
        migrations.AddField(
            model_name='campaign',
            name='food_items',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_order_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='running', max_length=100),
        ),
    ]
